# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install coveralls

script:
  - coverage erase
  - coverage run --timid -m unittest tests.coverage_unittest.unit_suite.test_unit_suite

after_success:
  - coveralls
