# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install coveralls

script:
  - coverage erase
  - coverage run --timid tests/test_suite/test_script_io.py
  - coverage run -a --timid tests/test_suite/test_script_inplace.py
  - coverage run -a --timid tests/test_suite/test_suite.py -d unittests
  - coverage run -a --timid tests/test_suite/test_suite.py -x test-python-sed.exclude @all-tests.suites

after_success:
  - coveralls
